apiVersion: v1
kind: Service
metadata:
        name: eap-ui-frontend-service
        labels:
                app: eap-ui-frontend
spec:
        ports:
                - name: eap-ui-frontend
                  port: 80
                  targetPort: 80
                  protocol: TCP
        selector:
                app: eap-ui-frontend
        type: ClusterIP
