apiVersion: v1
kind: Service
metadata:
        name: eap-ui-backend-service
spec:
        ports:
                - name: "http"
                  port: 13010
                  targetPort: 13010
        selector:
                app: eap-ui-backend
        type: NodePort
