apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: eap-ui-db-deployment
        labels:
                app: eap-ui-db
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: eap-ui-db
        template:
                metadata:
                        labels:
                                app: eap-ui-db
                spec:
                        containers:
                                - name: eap-ui-db
                                  image: mcr.microsoft.com/mssql/server:2019-latest
                                  ports:
                                        - conatinerPort: 1433
                                  env:
                                        - name: MSSQL_PID
                                          value: "Developer"
                                        - name: ACCEPT_EULA
                                          value: "Y"
                                        - name: SA_PASSWORD
                                          valueFrom:
                                                  secretKeyRef:
                                                          name: mssql
                                                          key: SA_PASSWORD
                                  volumeMounts:
                                        - name: mssqldb
                        volumes:
                                - name: mssqldb
                                  persistentVolumeClaim:
                                          claimName: mssql-data

