apiVersion: v1
kind: Service
metadata:
        name: awesome-media-backend-service
spec:
        ports:
                - name: "http"
                  port: 13010
                  targetPort: 13010
        selector:
                app: awesome-media-backend
        type: NodePort
