apiVersion: v1
kind: Service
metadata:
        name: iam-service
spec:
        ports:
                - name: "http"
                  port: 38080
                  targetPort: 38080
        selector:
                app: iam
        type: NodePort
