apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
        name: iam-deployment
        labels:
                app: iam
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: iam
        template:
                metadata:
                        labels:
                                app: iam
                spec:
                        containers:
                                - name: iam
                                  image: brotheroak/iam-service:1.0
                                  ports:
                                          - containerPort: 38080

                                  imagePullPolicy: Always
                                  env:
                                          - name: SPRING_PROFILES_ACTIVE
                                            value: k8s
                                          - name: MARIADB_USER
                                            value: root
                                          - name: MARIADB_PASSWORD
                                            value: miip
                                  resources:
                                          requests:
                                                  memory: "256Mi"
                                                  cpu: "0.25"
                                          limits:
                                                  memory: "1Gi"
                                                  cpu: "0.5"
