apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: miip-zuul-server-deployment
        labels:
                app: miip-zuul-server
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: miip-zuul-server
        template:
                metadata:
                        labels:
                                app: miip-zuul-server
                spec:
                        containers:
                                - name: miip-zuul-server
                                  image: brotheroak/miip-zuul-server:1.0
                                  ports:
                                          - containerPort: 20000
                                  imagePullPolicy: Always
                                  env:
                                          - name: SPRING_PROFILES_ACTIVE
                                            value: k8s

