apiVersion: v1
kind: Service
metadata:
        name: miip-mariadb
spec:
        ports:
                - name: "http"
                  port: 3306
                  targetPort: 3306
        selector:
                app: miip-mariadb
