apiVersion: v1
kind: Service
metadata:
        name: miip-zuul-server-service
spec:
        ports:
                - name: "http"
                  port: 20000
                  targetPort: 20000
        selector:
                app: miip-zuul-server
        type: NodePort
