apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: miip-eureka-server-deployment
        labels:
                app: miip-eureka-server
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: miip-eureka-server
        template:
                metadata:
                        labels:
                                app: miip-eureka-server
                spec:
                        containers:
                                - name: miip-eureka-server
                                  image: brotheroak/miip-eureka-server:1.0
                                  ports:
                                          - containerPort: 10002
                                  imagePullPolicy: Always
                                  env:
                                          - name: SPRING_PROFILES_ACTIVE
                                            value: k8s
                                  resource:
                                          requests:
                                                  memory: "256Mi"
                                                  cpu: "0.25"
                                          limits:
                                                  memory: "1Gi"
                                                  cpu: "0.5"

