apiVersion: v1
kind: Service
metadata:
        name: miip-eureka-server-service
spec:
        ports:
                - name: "http"
                  port: 10002
                  targetPort: 10002
        selector:
                app: miip-eureka-server
        type: NodePort
