apiVersion: v1
kind: Service
metadata:
        name: miip-config-server-service
spec:
        ports:
                - name: "http"
                  port: 10001
                  targetPort: 10001
        selector:
                app: miip-config-server
        type: NodePort
